export const ADMIN_ROUTER = '/admin'
export const LOGIN_ROUTER = '/login'
export const REGISTRATION_ROUTER = '/registration'
export const COLLECTIONS_ROUTER = '/collections'
export const ITEMS_ROUTER = '/items'
