export const ADMIN_ROUTER = '/admin'
export const LOGIN_ROUTER = '/login'
export const REGISTRATION_ROUTER = '/registration'
export const COLLECTION_ROUTER = '/collection'
export const ITEM_ROUTER = '/item'
export const USER_PAGE_ROUTER = '/user'