export const ADMIN_ROUTER = '/admin'
export const LOGIN_ROUTER = '/login'
export const REGISTRATION_ROUTER = '/registration'
export const COLLECTION_ID_ROUTER = '/collection/:id'
export const ITEM_ROUTER = '/item'
export const MY_COLLECTIONS_ROUTER = '/mycollections'
export const MY_COLLECTIONS_ID_ROUTER = '/mycollections/:id'
export const COLLECTION_ROUTER = '/collection'